<?php defined('BASEPATH') OR exit('No direct script access allowed');
$config['protocol'] = 'smtp';
$config['smtp_host'] = 'smtp.gmail.com';
$config['smtp_port'] = 465;
$config['smtp_user'] = 'rafamceti20@gmail.com';
$config['smtp_pass'] = 'DRkyangwe@2007';
$config['smtp_crypto'] = 'ssl';
$config['mailtype'] = 'text';
$config['charset'] ='8';
$config['charset'] = 'utf-8';
$config['wordwrap']  = TRUE;